namespace: nagios

bases:
- nagios
- auth-proxy
- ../../apps/nagios-api-checks

resources:
- namespace.yaml

images:

- name: nagios
  newName: gcr.io/stardust-156404/nagios
  newTag: h8

- name: oauth2-proxy
  newName: quay.io/oauth2-proxy/oauth2-proxy
  newTag: v7.1.2 # was v5.1.0

- name: nagios-api-checks
  newName: gcr.io/stardust-156404/nagios-api-checks
  newTag: h7

secretGenerator:
- name: nagios-api-checks
  env: api-checks.env
