namespace: nagios

bases:
- nagios
- auth-proxy
- ../../apps/nagios-api-checks

resources:
- namespace.yaml

images:
- name: nagios-api-checks
  newName: gcr.io/stardust-156404/nagios-api-checks
  newTag: h6

secretGenerator:
- name: nagios-api-checks
  env: api-checks.env
