namespace: skychat

images:

- name: dust-typescript
  newName: gcr.io/stardust-156404/dust-typescript
  newTag: 'fbd377d'

- name: stardriver-irc-modem
  newName: gcr.io/stardust-156404/stardriver-irc-dialer
  newTag: h16

- name: stardriver-coinbase-api-client
  newName: gcr.io/stardust-156404/coinbase-api-client
  newTag: h4

bases:
- ../../apps/stardriver-coinbase-api-client # for !btc
- irc-modem
# - ../../apps/bitlbee

# # human users
# - automatons/dan-irc
# # chatbots
# - automatons/skyhook-irc

resources:
- namespace.yaml
# - api-ingress.yaml
# - api-ingress-wg69.yaml

# patchesJson6902:
# - path: integrations-env-patch.yaml
#   target:
#     kind: StatefulSet
