namespace: skychat

images:

- name: dustjs-automaton-lua
  newName: gcr.io/stardust-156404/dustjs-automaton-lua
  newTag: '64c9168'
  # TODO:
  # newTag: '3cf0695'
  # TypeError: apiSession.wsDevice.invoke is not a function
  #   at /app/src/app.js:102:31

- name: stardriver-irc-modem
  newName: gcr.io/stardust-156404/stardriver-irc-dialer
  newTag: h16

- name: stardriver-coinbase-api-client
  newName: gcr.io/stardust-156404/coinbase-api-client
  newTag: h4

bases:
- ../../apps/stardriver-coinbase-api-client # for !btc
- irc-modem
# - ../../apps/bitlbee

# human users
- automatons/dan-irc
- automatons/nat-irc
- automatons/mkb-irc
- automatons/nb-irc
- automatons/fox-irc
- automatons/relrod-irc
- automatons/mykey-irc
# chatbots
- automatons/skyhook-irc

resources:
- namespace.yaml
# - api-ingress.yaml
# - api-ingress-wg69.yaml

# patchesJson6902:
# - path: integrations-env-patch.yaml
#   target:
#     kind: StatefulSet
