---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase-api-client
spec:
  replicas: 1
  template:
    spec:
      containers:

      - name: driver
        image: stardriver-coinbase-api-client
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 9234
          name: http
          protocol: TCP

        volumeMounts:
        - name: ca-certs
          mountPath: /etc/ssl/certs/ca-certificates.crt

        resources:
          requests:
            memory: 10Mi
            cpu: 5m
          limits:
            memory: 25Mi
            cpu: 1000m

      volumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
