apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase-api-client
spec:
  template:
    spec:

      nodeSelector:
        kubernetes.io/role: pet
        kubernetes.io/hostname: berbox

      tolerations:
      - key: kubernetes.io/pet-node
        operator: Exists
        effect: NoSchedule
