apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase-api-client
spec:
  template:
    spec:

      # We want a pet
      nodeSelector:
        lifetime: persistent
        purpose: pet

      # Passlist of pets we'll be ok with
      tolerations:
      - key: kubernetes.io/pet-node
        operator: Equal
        value: pet-laxbox
        effect: NoSchedule
      - key: kubernetes.io/pet-node
        operator: Equal
        value: pet-berbox
        effect: NoSchedule
