---
apiVersion: v1
kind: Service
metadata:
  name: coinbase-api-client
spec:
  type: ClusterIP
  publishNotReadyAddresses: true # TODO: kube-pet-node workaround
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9234
