---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-sync
spec:
  template:
    spec:

      containers:
      - name: app

        args:
        - --yes # no questions asked
        - --serve-metrics # openmetrics on 9090

        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json

        volumeMounts:
        - name: cfgmap
          mountPath: /src/kubernetes-dns-sync/config.toml
          subPath: config.toml

        - name: google-cloud-key
          mountPath: /var/secrets/google

      volumes:
      - name: cfgmap
        configMap:
          name: dns-sync-config
          defaultMode: 420

      - name: google-cloud-key
        secret:
          secretName: dns-sync-gcloud-key

      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Equal
        value: "true"
        effect: NoSchedule
