namespace: ingress-wg69
nameSuffix: -wg69
commonLabels:
  app.kubernetes.io/instance: wg69

bases:
- ../../../apps/kubernetes-dns-sync

patchesStrategicMerge:
- deployment.yaml

secretGenerator:
- name: dns-sync-gcloud-key
  files:
  - key.json=gcloud-key.json

configMapGenerator:
- name: dns-sync-config
  files:
  - config.toml

images:
- name: kubernetes-dns-sync
  newName: gcr.io/stardust-156404/kubernetes-dns-sync
  newTag: '2280a9e'
