---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: devmode.cloud-apex
spec:
  endpoints:

  - dnsName: devmode.cloud
    recordType: A
    targets:
    - '151.101.65.195'
    - '151.101.193.195'
    - '151.101.129.195'
    - '151.101.1.195'
  # - dnsName: devmode.cloud
  #   recordType: AAAA
  #   targets:
  #   - '2a04:4e42::451'
  #   - '2a04:4e42:600::451'
  #   - '2a04:4e42:200::451'
  #   - '2a04:4e42:400::451'
  # - dnsName: devmode.cloud
  #   recordType: NS
  #   targets:
  #   - 'ns1.vultr.com'
  #   - 'ns2.vultr.com'
  # - dnsName: devmode.cloud
  #   recordType: MX
  #   targets:
  #   - '10 mxa.mailgun.org'
  #   - '10 mxb.mailgun.org'
  - dnsName: devmode.cloud
    recordType: TXT
    targets:
    - "google-site-verification=nSd5rICjNGnYoSxPrQfBGc_K1TIHXbNzlOyxfAHW3ds"
    - "v=spf1 include:mailgun.org ~all"

  - dnsName: www.devmode.cloud
    recordType: CNAME
    targets:
    - 'devmode.cloud'

  # https://serverfault.com/questions/973666/do-intermediate-subdomains-need-to-exist
  - dnsName: pet.devmode.cloud
    recordType: A
    targets:
    - '0.0.0.0'

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: devmode.cloud-wireguard
spec:
  endpoints:

  - dnsName: wg1.devmode.cloud
    recordType: A
    targets:
    - '35.222.199.140'

  - dnsName: wg2.devmode.cloud
    recordType: A
    targets:
    - '144.202.24.201'

  - dnsName: wg2-dual.devmode.cloud
    recordType: A
    targets:
    - '144.202.24.201'
  - dnsName: wg2-dual.devmode.cloud
    recordType: AAAA
    targets:
    - '2001:19f0:5401:f15:5400:2ff:fe54:4fec'

  - dnsName: wg3.devmode.cloud
    recordType: CNAME
    targets:
    - 'berbox.pet.devmode.cloud'

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: devmode.cloud-modems
spec:
  endpoints:

  - dnsName: modem2.devmode.cloud
    recordType: A
    targets:
    - '52.36.135.46'
  - dnsName: modem2.devmode.cloud
    recordType: AAAA
    targets:
    - '2600:1f14:87f:f810:1d4a:46e9:bb1a:5593'

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: devmode.cloud-ingest
spec:
  endpoints:

  - dnsName: ingest.devmode.cloud
    recordType: CNAME
    targets:
    - 'd36fk5kn9ber0h.cloudfront.net'

  - dnsName: _3a3456f1b7bd9c5c6c48e941c1c98302.ingest.devmode.cloud
    recordType: CNAME
    targets:
    - '_bf0583decf4f5de5d30aa916097ae867.acm-validations.aws'
