configMapGenerator:

- name: multi-sqs-source
  files:
  - _host.js=src/_host.js
  - _lib.js=src/_lib.js
  - bugsnag.js=src/bugsnag.js
  - cloudwatch.js=src/cloudwatch.js
  - github.js=src/github.js
  - grafana.js=src/grafana.js
  - jenkins.js=src/jenkins.js
  - mailgun.js=src/mailgun.js
  - radarr.js=src/radarr.js
  - slackjack.js=src/slackjack.js
  - sonarr.js=src/sonarr.js
  - travisci.js=src/travisci.js
  - upcheck.js=src/upcheck.js
  - gitlab.js=src/gitlab.js
  - ombi.js=src/ombi.js
