apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: irc-modem
spec:
  template:
    spec:

      nodeSelector:
        # node-role.kubernetes.io/data-center: vultr
        kubernetes.io/hostname: worker-vultr-ordbox

      # Passlist of pets we'll be ok with
      # tolerations:
      # - key: kubernetes.io/pet-node
      #   operator: Equal
      #   value: pet-modem1
      #   effect: NoSchedule

      # This toleration would allow GKE nodes too
      # - key: cloud.google.com/gke-preemptible
      #   operator: Equal
      #   value: "false"
      #   effect: NoSchedule
