---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: reggie
spec:
  serviceName: reggie

  replicas: 1
  updateStrategy:
    type: RollingUpdate

  volumeClaimTemplates: []
  template:
    spec:
      containers:

      - name: bot
        image: reggie

        resources:
          requests:
            memory: 25Mi
            cpu: 10m
          limits:
            memory: 100Mi
            cpu: 250m

        volumeMounts:
        - name: config
          mountPath: /opt/reggie/config.yml
          subPath: config.yml

      volumes:
      - name: config
        configMap:
          name: reggie-config
