namespace: ingress-internet
nameSuffix: -internet
commonLabels:
  app.kubernetes.io/instance: internet

bases:
- ../../../apps/kubernetes-dns-sync

patchesStrategicMerge:
- deployment.yaml

secretGenerator:
- name: dns-sync-credentials
  env: credentials.env

configMapGenerator:
- name: dns-sync-config
  files:
  - config.toml
