apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-sqs
spec:
  template:
    spec:

      containers:
      - name: starnotify

        envFrom:
        - secretRef:
            name: credentials
