apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: starnotify

bases:
- ../../apps/starnotify-multi-sqs
- ../../apps/stardriver-irc-client
- ../../apps/skyhook-irc-outbound
resources:
- serviceaccount-iam.yaml

patches:
- deployment-env.yaml
# deployments get deleted whenever
- preemptible-pods.yaml
# statefulsets stay running
- persistent-pods.yaml

secretGenerator:
- env: credentials.env
  name: credentials

- env: irc-outbound.env
  name: irc-outbound-env

images:

- name: gcr.io/stardust-156404/multi-starnotify-deps
  newTag: h25

- name: skyhook-irc-outbound
  newName: gcr.io/stardust-156404/skyhook-irc-outbound
  newTag: h7
