apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-sqs
spec:
  template:
    spec:

      # nodeSelector:
      #   lifetime: preemptible

      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Equal
        value: "true"
        effect: NoSchedule

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: irc-outbound
spec:
  template:
    spec:

      # nodeSelector:
      #   lifetime: preemptible

      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Equal
        value: "true"
        effect: NoSchedule
