apiVersion: apps/v1
kind: not-important
metadata:
  name: not-important
spec:
  template:
    spec:

      nodeSelector:
        lifetime: preemptible

      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Equal
        value: "true"
        effect: NoSchedule
