apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-to-dd-loop
spec:
  template:
    spec:

      containers:
      - name: loop

        envFrom:
        - secretRef:
            name: ship-to-dd-credentials
