---
apiVersion: v1
kind: Service
metadata:
  name: srv
spec:
  publishNotReadyAddresses: true # TODO: kube-pet-node workaround
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: http
