---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-sync
spec:
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: dns-sync
      containers:
      - name: app
        image: kubernetes-dns-sync

        command:
        - "deno"
        - "run"
        - "--allow-net"
        - "--allow-read"
        - "--allow-env"
        - "--cert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        - "--cached-only"
        - "controller/mod.ts"

        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
