---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-dns-sync
spec:
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: kubernetes-dns-sync
      containers:
      - name: kubernetes-dns-sync
        image: kubernetes-dns-sync

        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
