apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-dns-sync
spec:
  template:
    spec:

      # We want a pet
      nodeSelector:
        lifetime: persistent
        purpose: pet

      # Doesn't matter which
      tolerations:
      - key: kubernetes.io/pet-node
        operator: Exists
        effect: NoSchedule
