namespace: nagios
commonLabels:
  app: nagios
  component: controller

resources:
- statefulset.yaml
- service.yaml

configMapGenerator:

- name: httpd-conf
  files:
  - nagios.conf=httpd-conf/nagios.conf
  - php.conf=httpd-conf/php.conf
