---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nagios
spec:
  serviceName: nagios

  replicas: 1
  updateStrategy:
    type: RollingUpdate

  template:
    spec:
      terminationGracePeriodSeconds: 5
      shareProcessNamespace: true
      containers:

      - name: nagios
        image: nagios
        args:
        - sh
        - -exc
        - |
          chown nagios:nagios /var/spool/nagios
          chown nagios:nagios /var/log/nagios
          exec /usr/sbin/nagios /etc/nagios/nagios.cfg
        resources:
          requests:
            cpu: 25m
            memory: 25Mi
          limits:
            cpu: 1500m
            memory: 75Mi
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        # split the persisted volume into three places
        - name: data
          mountPath: /etc/nagios
          subPath: etc
        - name: data
          mountPath: /var/spool/nagios
          subPath: spool
        - name: data
          mountPath: /var/log/nagios
          subPath: log

      - name: httpd
        image: nagios
        args:
        - /usr/sbin/apachectl
        - -DFOREGROUND
        resources:
          requests:
            cpu: 25m
            memory: 25Mi
          limits:
            cpu: 1500m
            memory: 75Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 60
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: httpd-conf
          mountPath: /etc/httpd/conf.d
        # split the persisted volume into three places
        - name: data
          mountPath: /etc/nagios
          subPath: etc
        - name: data
          mountPath: /var/spool/nagios
          subPath: spool
        - name: data
          mountPath: /var/log/nagios
          subPath: log

      initContainers:
      - name: setup
        image: nagios
        command:
        - sh
        - -exc
        - |
          #rm -rf /mnt/etc/*

          if [ ! -d /mnt/etc ]
          then cp -a /etc/nagios /mnt/etc
          echo default_user_name=vpnuser >> /mnt/etc/cgi.cfg
          echo authorized_for_read_only=vpnuser >> /mnt/etc/cgi.cfg
          sed -Ei.bak '/^url_html_path=/s#=/.+$#=/#' /mnt/etc/cgi.cfg
          sed -Ei.bak '/^authorized_for_/s#=.+$#=dan@danopia.net,rick@elrod.me#' /mnt/etc/cgi.cfg
          fi

          if [ ! -d /mnt/spool ]
          then cp -a /var/spool/nagios /mnt/spool
          fi

          if [ ! -d /mnt/log ]
          then cp -a /var/log/nagios /mnt/log
          fi

        volumeMounts:
        - name: data
          mountPath: /mnt

      volumes:
      - name: httpd-conf
        configMap:
          name: httpd-conf

  volumeClaimTemplates:

  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
