---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: automaton
spec:
  serviceName: dustjs-automaton

  replicas: 1
  updateStrategy:
    type: RollingUpdate

  volumeClaimTemplates: []
  template:
    spec:
      containers:

      - name: app
        image: dust-typescript

        command:
        - deno
        - run
        - --allow-net
        - --allow-env
        - --allow-read
        - --cached-only
        - automaton-lua/app.ts

        envFrom:
        - secretRef:
            name: automaton-env

        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 1000m
            memory: 128Mi

      # don't care about preemptible status
      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Exists
        effect: NoSchedule
