---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-sqs
  labels:
    starnotify: multi-sqs
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        starnotify: multi-sqs
    spec:
      containers:
      - name: starnotify
        image: multi-starnotify-deps
        args:
        - 'node'
        - 'src/_host'
        env:
        - name: SQS_QUEUE_URL_BASE
          value: https://sqs.us-west-2.amazonaws.com/414064234042/
        - name: VIEWING_TIMEZONE
          value: America/Los_Angeles

        volumeMounts:
        - name: source
          mountPath: /src

      volumes:
      - name: source
        configMap:
          name: multi-sqs-source
