apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-sqs
spec:
  template:
    spec:
      containers:
      - name: starnotify

        resources:
          requests:
            cpu: 5m
            memory: 30Mi
          limits:
            cpu: 1000m
            memory: 50Mi
