apiVersion: apps/v1beta2
kind: not-important
metadata:
  name: not-important
spec:
  template:
    spec:

      nodeSelector:
        # lifetime: persistent
        kubernetes.io/hostname: worker-vultr-frabox

      # tolerations:
      # - key: cloud.google.com/gke-preemptible
      #   operator: Equal
      #   value: "false"
      #   effect: NoSchedule
