namespace: nagios

bases:
- ../../apps/nagios
- ../../apps/nagios-api-checks

resources:
- auth-proxy.yaml
- serviceaccount.yaml
- rbac.yaml

images:
- name: nagios
  newName: gcr.io/stardust-156404/nagios
  newTag: h4
- name: nagios-api-checks
  newName: gcr.io/stardust-156404/nagios-api-checks
  newTag: h4

patches:

- path: preemptible-pods.yaml
  target:
    kind: StatefulSet
- path: wireguard-sidecar.yaml
  target:
    kind: StatefulSet
- path: serviceaccount-assignment.yaml
  target:
    kind: StatefulSet

secretGenerator:

- name: nagios-oauth
  env: auth-proxy.env

- name: nagios-api-checks
  env: api-checks.env

- name: wireguard-key
  env: wireguard.env

configMapGenerator:

- name: nagios-auth-config
  files:
  - email_list.txt
  - oauth2_proxy.cfg

- name: wireguard-conf
  files:
  - wg0.conf=wireguard.conf
