apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: build-shell
spec:
  serviceName: build-shell
  volumeClaimTemplates: []
  template:
    spec:
      containers:
      - name: build-shell
        image: gcr.io/stardust-156404/build-shell
        securityContext:
          privileged: true
      nodeSelector:
        purpose: build
      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Equal
        value: "true"
        effect: NoSchedule
      - key: node-purpose
        operator: Equal
        value: "build"
        effect: NoSchedule
