---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: irc-modem
spec:

  updateStrategy:
    type: OnDelete

  template:
    spec:
      containers:

      - name: driver
        image: stardriver-irc-modem

        ports:
        - containerPort: 9234
          name: http
          protocol: TCP

        volumeMounts:
        - name: ca-certs
          mountPath: /etc/ssl/certs/ca-certificates.crt

        resources:
          requests:
            memory: 100Mi
            cpu: 10m
          limits:
            memory: 100Mi
            cpu: 1000m

      volumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
