kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-runner
subjects:
- kind: ServiceAccount
  name: drone-k8s-runner
  namespace: drone-gitea
roleRef:
  kind: Role
  name: drone-runner
  apiGroup: rbac.authorization.k8s.io
