namespace: dust-poc

bases:
- ../../apps/dust-poc
resources:
- namespace.yaml
- ingress.yaml

patchesStrategicMerge:
- serviceaccount-iam.yaml

images:
- name: gcr.io/stardust-156404/dust-poc
  newName: gcr.io/stardust-156404/dust-poc-kubectl
  newTag: a543f57
