---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-to-dd-loop
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    spec:
      serviceAccountName: ship-to-dd-sa
      containers:
      - name: loop
        image: hayd/alpine-deno
        args:
        - deno
        - run
        - "--allow-net"
        - "--allow-read"
        - "--allow-env"
        - "--cert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        - /src/mod.ts

        resources:
          requests:
            cpu: 5m
            memory: 30Mi
          limits:
            cpu: 500m
            memory: 200Mi

        volumeMounts:
        - name: source
          mountPath: /src

      volumes:
      - name: source
        configMap:
          name: ship-to-dd-src
