---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-to-dd-loop
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        cloudydeno.github.io/metrics: 'true'
      annotations:
        cloudydeno.github.io/metric-port: '9090'
    spec:
      serviceAccountName: ship-to-dd-sa
      containers:
      - name: loop
        image: kubernetes-ship-to-datadog

        args:
        - "--serve-metrics"

        resources:
          requests:
            cpu: 5m
            memory: 30Mi
          limits:
            cpu: 500m
            memory: 200Mi
