# namePrefix: ship-to-dd-
commonLabels:
  app.kubernetes.io/name: kubernetes-ship-to-dd

resources:
- deployment.yaml
- serviceaccount.yaml
- rbac.yaml

images:
- name: kubernetes-ship-to-datadog
  newName: ghcr.io/cloudydeno/kubernetes-ship-to-datadog
  digest: sha256:855af25dad524732a2328dce3f7ff1ec9b02887ed538c95fb86d12a7416becc8
