apiVersion: v1
kind: ServiceAccount
metadata:
  name: srv

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::414064234042:role/gke-code-server

# imagePullSecrets:
# - name: stardust-gcr.io
