apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
- ../../../apps/reggie
patches:
- node-assignment.yaml

configMapGenerator:
- name: reggie-config
  files:
  - config.yml

images:
- name: gcr.io/stardust-156404/reggie
  newTag: h12
