apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
- ../../../apps/reggie
patches:
- node-assignment.yaml

configMapGenerator:
- name: reggie-config
  files:
  - config.yml

images:
- name: reggie
  newName: rg.fr-par.scw.cloud/danopia-public/reggie
  newTag: h12
