apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fe
  annotations:
    # external-dns.alpha.kubernetes.io/ttl: "120"
    kubernetes.io/ingress.class: internet
    cert-manager.io/cluster-issuer: dns-sync-issuer
spec:
  ingressClassName: internet
  tls:
  - hosts:
    - nagios.devmode.cloud
    secretName: tls-nagios.devmode.cloud
  rules:
  - host: nagios.devmode.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proxy
            port:
              number: 80
