namespace: ingress-internet

bases:
- ../../../apps/ingress-nginx
resources:
- namespace.yaml

patches: #Json6902:

- path: patch-role.yaml
  target:
    kind: Role
    name: nginx-ingress-role

- path: patch-crb.yaml
  target:
    kind: ClusterRoleBinding
    name: nginx-ingress-clusterrole-nisa-binding

- path: patch-service.yaml
  target:
    kind: Service
    name: ingress-nginx

# Configure daemon to publish correct IPs
- path: patch-container-args.yaml
  target:
    kind: Deployment
    name: nginx-ingress-controller

# Listen on the host 80/443
- path: patch-host-ports.yaml
  target:
    kind: Deployment
    name: nginx-ingress-controller

# internet-facing NGINX stays running
- path: persistent-pods-patch.yaml
  target:
    kind: Deployment

# Convert into a DaemonSet to run exactly 1 per node
- path: patch-to-daemonset.yaml
  target:
    kind: Deployment
    name: nginx-ingress-controller
