- op: test
  path: '/spec/template/spec/containers/0/args/4'
  value: --publish-service=$(POD_NAMESPACE)/ingress-nginx
- op: replace
  path: '/spec/template/spec/containers/0/args/4'
  value: --report-node-internal-ip-address=false

- op: add
  path: '/spec/template/spec/containers/0/args/6'
  value: --ingress-class=internet
