---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Equal
        value: "true"
        effect: NoSchedule

      containers:
      - name: external-dns
        args:
        - --source=ingress
        - --events
        - --interval=30m
        # - --annotation-filter=kubernetes.io/ingress.class=wg69
        - --zone-id-filter=wg69net-int
        - --provider=google
        - --google-project=stardust-156404
        - --registry=txt
        - --txt-owner-id=dust-usc1f-int
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
      volumes:
      - name: google-cloud-key
        secret:
          secretName: external-dns-gcloud-key
