---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: srv
spec:
  template:
    spec:
      containers:
      - name: srv

        image: linuxserver/sabnzbd
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

        # resources:
        #   requests:
        #     memory: 100Mi
        #     cpu: 50m
        #   limits:
        #     memory: 150Mi
        #     cpu: 1000m

        volumeMounts:
        - name: config
          mountPath: /config
        - name: tv
          mountPath: /downloads/tv
        - name: movies
          mountPath: /downloads/movies

      volumes:
      - name: config
        hostPath:
          path: /tank/data/sabnzbd
          type: Directory
      - name: tv
        hostPath:
          path: /tank/media/tv/downloads
          type: Directory
      - name: movies
        hostPath:
          path: /tank/media/movies/downloads
          type: Directory
