---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pet-update
rules:
- apiGroups:
  - pet.wg69.net
  resources:
  - blockdevices
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pet-update
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pet-update
subjects:
- kind: ServiceAccount
  name: loop
