apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - pet.wg69.net
  resources:
  - blockdevices
  verbs:
  - get
  - list
  - watch
