namespace: nagios

bases:
- ../../../apps/nagios

resources:
- serviceaccount.yaml
- rbac.yaml
- storageclass.yaml
- persistent-volume.yaml

patches:
# - node-assignment.yaml
# - wg-sidecar.yaml
# - tailscale-sidecar.yaml
- serviceaccount-assignment.yaml

- persistent-volume-assignment.yaml

# secretGenerator:
# - name: wireguard-key
#   env: wg-keypair.env

# - name: tailscale-state
#   files:
#   - tailscale-key.json

# configMapGenerator:
# - name: wireguard-conf
#   files:
#   - wg0.conf
