namespace: nagios

bases:
- ../../../apps/nagios

resources:
- serviceaccount.yaml
- rbac.yaml

patches:
- node-assignment.yaml
- wg-sidecar.yaml
- serviceaccount-assignment.yaml

secretGenerator:
- name: wireguard-key
  env: wg-keypair.env

configMapGenerator:
- name: wireguard-conf
  files:
  - wg0.conf
