apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nagios
spec:

  volumeClaimTemplates:

  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: nagios-storage
      resources:
        requests:
          storage: 1Gi
