---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: grab-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: nagios-grab-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grab-secrets
subjects:
- kind: ServiceAccount
  name: nagios
